package com.bbl.cache.template;
// Generated Jan 26, 2026, 10:29:52 AM by Hibernate Tools 7.2.1.Final




import java.io.Serial;
import java.io.Serializable;
import java.util.Objects;

/**
 * AnygwcompprofileId generated by hbm2java
 */

public class AnygwcompprofileId implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    private String bpmBillerId;

    private String compId;

    private String serviceName;

    protected AnygwcompprofileId() {
    }

    public AnygwcompprofileId(String bpmBillerId, String compId, String serviceName) {
        this.bpmBillerId = Objects.requireNonNull(bpmBillerId, "bpmBillerId must not be null.");
        this.compId = Objects.requireNonNull(compId, "compId must not be null.");
        this.serviceName = Objects.requireNonNull(serviceName, "serviceName must not be null.");
    }

    public String getBpmBillerId() {
        return this.bpmBillerId;
    }

    public String getCompId() {
        return this.compId;
    }

    public String getServiceName() {
        return this.serviceName;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof AnygwcompprofileId id)) {
            return false;
        }

        return Objects.equals(bpmBillerId, id.bpmBillerId)
                && Objects.equals(compId, id.compId)
                && Objects.equals(serviceName, id.serviceName);

    }

    @Override
    public int hashCode() {
        return Objects.hash(bpmBillerId, compId, serviceName);
    }


    @Override
    public String toString() {
        return "AnygwcompprofileId{" +
                "bpmBillerId='" + bpmBillerId + '\'' +
                ", compId='" + compId + '\'' +
                ", serviceName='" + serviceName + '\'' +
                '}';
    }
}


