package com.bbl.cache.template;
// Generated Jan 26, 2026, 10:29:52 AM by Hibernate Tools 7.2.1.Final



import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * Anygwcompprofile generated by hbm2java
 */

public class Anygwcompprofile implements Serializable {


    private AnygwcompprofileId id;

    private String compCode;

    private String compNameEn;

    private String compNameTh;

    private String contact;

    private char serviceHoliday;

    private LocalDate serviceFromTime;

    private LocalDate serviceToTime;

    private String virtualCard;

    private String compAcct;

    private String bpmServiceCode;

    private String businessOwner;

    private String compIdIs;

    private BigDecimal maxTxnlimit;

    private BigDecimal minTxnlimit;

    private String customerType;

    private String organize;

    private String clientId;

    private String countryCode;

    private BigDecimal othbkMinTxnlimit;

    private BigDecimal othbkMaxTxnlimit;
    private Character recvNameMatching;

    private LocalDate registerDate;

    private LocalDate updateDate;


    protected Anygwcompprofile() {
    }


    public Anygwcompprofile(AnygwcompprofileId id) {
        this.id = Objects.requireNonNull(id, "Id must not be null.");
    }


    public AnygwcompprofileId getId() {
        return this.id;
    }


    public String getCompCode() {
        return this.compCode;
    }

    public void setCompCode(String compCode) {
        this.compCode = compCode;
    }


    public String getCompNameEn() {
        return this.compNameEn;
    }

    public void setCompNameEn(String compNameEn) {
        this.compNameEn = compNameEn;
    }


    public String getCompNameTh() {
        return this.compNameTh;
    }

    public void setCompNameTh(String compNameTh) {
        this.compNameTh = compNameTh;
    }


    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }


    public char getServiceHoliday() {
        return this.serviceHoliday;
    }

    public void setServiceHoliday(char serviceHoliday) {
        this.serviceHoliday = serviceHoliday;
    }


    public LocalDate getServiceFromTime() {
        return this.serviceFromTime;
    }

    public void setServiceFromTime(LocalDate serviceFromTime) {
        this.serviceFromTime = serviceFromTime;
    }


    public LocalDate getServiceToTime() {
        return this.serviceToTime;
    }

    public void setServiceToTime(LocalDate serviceToTime) {
        this.serviceToTime = serviceToTime;
    }


    public String getVirtualCard() {
        return this.virtualCard;
    }

    public void setVirtualCard(String virtualCard) {
        this.virtualCard = virtualCard;
    }


    public String getCompAcct() {
        return this.compAcct;
    }

    public void setCompAcct(String compAcct) {
        this.compAcct = compAcct;
    }


    public String getBpmServiceCode() {
        return this.bpmServiceCode;
    }

    public void setBpmServiceCode(String bpmServiceCode) {
        this.bpmServiceCode = bpmServiceCode;
    }


    public String getBusinessOwner() {
        return this.businessOwner;
    }

    public void setBusinessOwner(String businessOwner) {
        this.businessOwner = businessOwner;
    }


    public String getCompIdIs() {
        return this.compIdIs;
    }

    public void setCompIdIs(String compIdIs) {
        this.compIdIs = compIdIs;
    }


    public BigDecimal getMaxTxnlimit() {
        return this.maxTxnlimit;
    }

    public void setMaxTxnlimit(BigDecimal maxTxnlimit) {
        this.maxTxnlimit = maxTxnlimit;
    }


    public BigDecimal getMinTxnlimit() {
        return this.minTxnlimit;
    }

    public void setMinTxnlimit(BigDecimal minTxnlimit) {
        this.minTxnlimit = minTxnlimit;
    }


    public String getCustomerType() {
        return this.customerType;
    }

    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }


    public String getOrganize() {
        return this.organize;
    }

    public void setOrganize(String organize) {
        this.organize = organize;
    }


    public String getClientId() {
        return this.clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }


    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }


    public BigDecimal getOthbkMinTxnlimit() {
        return this.othbkMinTxnlimit;
    }

    public void setOthbkMinTxnlimit(BigDecimal othbkMinTxnlimit) {
        this.othbkMinTxnlimit = othbkMinTxnlimit;
    }


    public BigDecimal getOthbkMaxTxnlimit() {
        return this.othbkMaxTxnlimit;
    }

    public void setOthbkMaxTxnlimit(BigDecimal othbkMaxTxnlimit) {
        this.othbkMaxTxnlimit = othbkMaxTxnlimit;
    }


    public Character getRecvNameMatching() {
        return this.recvNameMatching;
    }

    public void setRecvNameMatching(Character recvNameMatching) {
        this.recvNameMatching = recvNameMatching;
    }


    public LocalDate getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(LocalDate registerDate) {
        this.registerDate = registerDate;
    }


    public LocalDate getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDate updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        return "Anygwcompprofile{" +
                "id=" + id +
                ", compCode='" + compCode + '\'' +
                ", compNameEn='" + compNameEn + '\'' +
                ", compNameTh='" + compNameTh + '\'' +
                ", contact='" + contact + '\'' +
                ", serviceHoliday=" + serviceHoliday +
                ", serviceFromTime=" + serviceFromTime +
                ", serviceToTime=" + serviceToTime +
                ", virtualCard='" + virtualCard + '\'' +
                ", compAcct='" + compAcct + '\'' +
                ", bpmServiceCode='" + bpmServiceCode + '\'' +
                ", businessOwner='" + businessOwner + '\'' +
                ", compIdIs='" + compIdIs + '\'' +
                ", maxTxnlimit=" + maxTxnlimit +
                ", minTxnlimit=" + minTxnlimit +
                ", customerType='" + customerType + '\'' +
                ", organize='" + organize + '\'' +
                ", clientId='" + clientId + '\'' +
                ", countryCode='" + countryCode + '\'' +
                ", othbkMinTxnlimit=" + othbkMinTxnlimit +
                ", othbkMaxTxnlimit=" + othbkMaxTxnlimit +
                ", recvNameMatching=" + recvNameMatching +
                ", registerDate=" + registerDate +
                ", updateDate=" + updateDate +
                '}';
    }
}


